import { Task } from "../types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Complete Project Proposal",
    description: "Draft and finalize the Q2 project proposal for client review.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-10T10:00:00Z",
    dueDate: "2024-01-20",
  },
  {
    id: "2",
    title: "Review Code Changes",
    description: "Review pull requests and merge approved changes.",
    status: "completed",
    priority: "medium",
    createdAt: "2024-01-11T09:00:00Z",
    dueDate: "2024-01-16",
  },
  {
    id: "3",
    title: "Update Documentation",
    description: "Update API documentation with new endpoints.",
    status: "incomplete",
    priority: "low",
    createdAt: "2024-01-12T14:00:00Z",
    dueDate: "2024-01-18",
  },
  {
    id: "4",
    title: "Client Meeting Preparation",
    description: "Prepare presentation and demos for client meeting.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-13T11:00:00Z",
    dueDate: "2024-01-17",
  },
  {
    id: "5",
    title: "Bug Fixes in Login Module",
    description: "Address reported bugs in the login module.",
    status: "completed",
    priority: "high",
    createdAt: "2024-01-14T13:00:00Z",
    dueDate: "2024-01-15",
  },
  {
    id: "6",
    title: "Team Meeting",
    description: "Schedule and conduct the weekly team meeting.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-01-14T15:00:00Z",
    dueDate: "2024-01-15",
  },
  {
    id: "7",
    title: "Test Feature X",
    description: "Perform end-to-end testing on the new feature X.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-15T09:00:00Z",
    dueDate: "2024-01-19",
  },
  {
    id: "8",
    title: "Deploy Hotfix",
    description: "Deploy urgent hotfix to production environment.",
    status: "completed",
    priority: "high",
    createdAt: "2024-01-16T08:30:00Z",
    dueDate: "2024-01-16",
  },
  {
    id: "9",
    title: "Prepare Sales Report",
    description: "Compile and analyze sales data for Q1.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-01-17T10:00:00Z",
    dueDate: "2024-01-22",
  },
  {
    id: "10",
    title: "Optimize Database Queries",
    description: "Improve the performance of critical database queries.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-18T13:00:00Z",
    dueDate: "2024-01-25",
  },
  {
    id: "11",
    title: "Design Mockups",
    description: "Create design mockups for the new landing page.",
    status: "completed",
    priority: "medium",
    createdAt: "2024-01-19T11:30:00Z",
    dueDate: "2024-01-21",
  },
  {
    id: "12",
    title: "User Feedback Analysis",
    description: "Analyze user feedback to identify common issues.",
    status: "incomplete",
    priority: "low",
    createdAt: "2024-01-20T09:00:00Z",
    dueDate: "2024-01-26",
  },
  {
    id: "13",
    title: "Code Refactoring",
    description: "Refactor code to improve maintainability.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-01-21T12:00:00Z",
    dueDate: "2024-01-28",
  },
  {
    id: "14",
    title: "Conduct Training Session",
    description: "Organize and lead a training session for new hires.",
    status: "completed",
    priority: "low",
    createdAt: "2024-01-22T10:00:00Z",
    dueDate: "2024-01-23",
  },
  {
    id: "15",
    title: "Marketing Strategy Update",
    description: "Update the marketing strategy for Q2.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-23T14:00:00Z",
    dueDate: "2024-01-30",
  },
  {
    id: "16",
    title: "Research Competitor Products",
    description: "Research features of competitor products for inspiration.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-01-24T13:00:00Z",
    dueDate: "2024-01-29",
  },
  {
    id: "17",
    title: "Run Security Audit",
    description: "Perform a comprehensive security audit of the system.",
    status: "completed",
    priority: "high",
    createdAt: "2024-01-25T10:30:00Z",
    dueDate: "2024-01-27",
  },
  {
    id: "18",
    title: "Fix UI Bugs",
    description: "Resolve reported UI issues in the dashboard.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-01-26T09:00:00Z",
    dueDate: "2024-01-31",
  },
  {
    id: "19",
    title: "Prepare Budget Proposal",
    description: "Draft the budget proposal for the upcoming fiscal year.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-27T10:00:00Z",
    dueDate: "2024-02-05",
  },
  {
    id: "20",
    title: "Conduct User Interviews",
    description: "Arrange interviews with users to gather feedback.",
    status: "completed",
    priority: "low",
    createdAt: "2024-01-28T11:00:00Z",
    dueDate: "2024-02-03",
  },
  {
    id: "21",
    title: "Finalize App Design",
    description: "Complete the design for the new mobile application.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-01-29T14:00:00Z",
    dueDate: "2024-02-07",
  },
  {
    id: "22",
    title: "Server Maintenance",
    description: "Perform scheduled maintenance on the servers.",
    status: "completed",
    priority: "medium",
    createdAt: "2024-01-30T08:00:00Z",
    dueDate: "2024-01-31",
  },
  {
    id: "23",
    title: "Publish Blog Post",
    description: "Write and publish a blog post on the company website.",
    status: "incomplete",
    priority: "low",
    createdAt: "2024-01-31T10:00:00Z",
    dueDate: "2024-02-04",
  },
  {
    id: "24",
    title: "Upgrade Dependencies",
    description: "Update project dependencies to the latest versions.",
    status: "completed",
    priority: "medium",
    createdAt: "2024-02-01T09:30:00Z",
    dueDate: "2024-02-02",
  },
  {
    id: "25",
    title: "Plan Product Launch",
    description: "Create a roadmap for the product launch event.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-02-02T11:00:00Z",
    dueDate: "2024-02-10",
  },
  {
    id: "26",
    title: "Set Up Analytics",
    description: "Implement analytics tracking on the web application.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-02-03T12:30:00Z",
    dueDate: "2024-02-08",
  },
  {
    id: "27",
    title: "Prepare Employee Handbook",
    description: "Update and distribute the employee handbook.",
    status: "completed",
    priority: "low",
    createdAt: "2024-02-04T10:00:00Z",
    dueDate: "2024-02-06",
  },
  {
    id: "28",
    title: "Review Marketing Campaign",
    description: "Analyze the performance of the recent marketing campaign.",
    status: "incomplete",
    priority: "medium",
    createdAt: "2024-02-05T13:00:00Z",
    dueDate: "2024-02-09",
  },
  {
    id: "29",
    title: "Improve App Onboarding",
    description: "Enhance the user onboarding process for the app.",
    status: "incomplete",
    priority: "high",
    createdAt: "2024-02-06T14:30:00Z",
    dueDate: "2024-02-12",
  },
  {
    id: "30",
    title: "Prepare Annual Report",
    description: "Compile and publish the annual financial report.",
    status: "completed",
    priority: "high",
    createdAt: "2024-02-07T10:00:00Z",
    dueDate: "2024-02-15",
  },
];
